spring:
  application:
    name: esp32
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://localhost:8889/pi-one
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

server:
  forward-headers-strategy: native
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /api

esp:
  server:
    mqttPwd: tatayoyo@
    port: 8081
